version: '3.9'

services:
  mysql-container:

    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springBatch
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 50s
      retries: 3
    restart: on-failure

  springbatch-app:
    image: springbatch-app:latest

    ports:
      - "9191:9191"
    environment:
      MYSQL_URL: mysql-container
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root


    # Uncomment this one if you want to build from Dockerfile

    build:
      context: .
      dockerfile: "Dockerfile"
    depends_on:
      mysql-container:
        condition: service_healthy






